$(document).ready(()=>{
    $('p').click(()=>{
        if($('button').hasClass('btn')){
            $('button').removeClass('btn');
        }else{
            $('button').addClass('btn');
        }
    });
});
